services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-blockchain-txs
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-blockchain-txs-network
    volumes:
      - './local-dev/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro'
      - './local-dev/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro'

networks:
  rabbitmq-blockchain-txs-network:
    driver: bridge