{
 "title": "NestJS Blockchain Txs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_txs_in_blockchain", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(total_txs_rejected)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentagem of mined coins",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(total_coins_mined) * 100 / (total_coins_mined + total_coins_left_to_mine)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blockchain status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "blockchain_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_addresses", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions rejected causes",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "targets": [
    { "expr": "total_txs_rejected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mined coins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_coins_mined", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Coins left to mine",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_coins_left_to_mine", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transferred coins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_coins_transfered", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Minning rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_mining_rewards", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average blocks mining time history (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "total_block_mining_time / total_blocks_mined",
     "legendFormat": "Average blocks mining time history (seconds)"
    }
   ]
  },
  {
   "title": "Total blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_blocks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blocks rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_blocks_rejected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg. block mining time (sec.)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_block_mining_time / total_blocks_mined",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}